import { NauticalProviderMeta } from '../types/nautical'

export const nauticalProviders: NauticalProviderMeta[] = [
  {
    id: 'openseamap',
    name: 'OpenSeaMap',
    tier: 'free',
    type: 'tile',
    description: 'Nautical marks, buoys, lights, and other seamark overlays on OpenStreetMap.',
    website: 'https://openseamap.org',
    pros: ['Completely free', 'Community maintained', 'Global coverage'],
    cons: ['Limited detail in some regions', 'Community-dependent updates'],
    requiresApiKey: false,
  },
  {
    id: 'noaa-charts',
    name: 'NOAA Charts',
    tier: 'free',
    type: 'tile',
    description: 'Official US nautical charts from NOAA via WMTS tile service.',
    website: 'https://charts.noaa.gov',
    pros: ['Official government data', 'High accuracy for US waters', 'Free to use'],
    cons: ['US waters only', 'Can be slow to update'],
    requiresApiKey: false,
  },
  {
    id: 'gebco',
    name: 'GEBCO Bathymetry',
    tier: 'free',
    type: 'tile',
    description: 'Global bathymetry and ocean depth visualization via WMS.',
    website: 'https://www.gebco.net',
    pros: ['Global ocean depth data', 'Free to use', 'Scientific quality'],
    cons: ['Lower resolution in some areas', 'WMS can be slower than tile sources'],
    requiresApiKey: false,
  },
  {
    id: 'noaa-coops',
    name: 'NOAA CO-OPS',
    tier: 'free',
    type: 'data',
    description: 'Real-time and predicted tide and current data from US stations.',
    website: 'https://tidesandcurrents.noaa.gov',
    pros: ['Official NOAA data', 'Real-time observations', 'Tide predictions'],
    cons: ['US stations only', 'Rate limited'],
    requiresApiKey: false,
  },
  {
    id: 'aisstream',
    name: 'AISstream.io',
    tier: 'free',
    type: 'data',
    description: 'Real-time coastal AIS vessel tracking via WebSocket.',
    website: 'https://aisstream.io',
    pros: ['Real-time vessel positions', 'WebSocket streaming', 'Free tier available'],
    cons: ['Requires free API key', 'Coastal coverage only'],
    requiresApiKey: true,
    apiKeySignupUrl: 'https://aisstream.io/authenticate',
  },
  {
    id: 'open-meteo',
    name: 'Open-Meteo Marine',
    tier: 'free',
    type: 'data',
    description: 'Marine weather forecasts including wave height, swell, and wind.',
    website: 'https://open-meteo.com',
    pros: ['Completely free', 'No API key needed', 'Global coverage'],
    cons: ['Forecast only, no observations', 'Less detail than paid alternatives'],
    requiresApiKey: false,
  },
  {
    id: 'worldtides',
    name: 'WorldTides',
    tier: 'paid',
    type: 'data',
    description: 'Global tide predictions and observations with high accuracy.',
    website: 'https://www.worldtides.info',
    pros: ['Global coverage', 'High accuracy', 'Detailed predictions'],
    cons: ['Paid per request', 'Credits expire'],
    requiresApiKey: true,
    apiKeySignupUrl: 'https://www.worldtides.info/developer',
    pricingNote: '$10 for 5,000 predictions',
  },
  {
    id: 'stormglass',
    name: 'Stormglass',
    tier: 'paid',
    type: 'data',
    description: 'Premium marine weather data from multiple sources.',
    website: 'https://stormglass.io',
    pros: ['Multiple weather models', 'High accuracy', 'Free tier (10 req/day)'],
    cons: ['Limited free tier', 'Can be expensive at scale'],
    requiresApiKey: true,
    apiKeySignupUrl: 'https://stormglass.io/register',
    pricingNote: 'Free tier: 10 requests/day. Paid plans from $19/month.',
  },
  {
    id: 'windy',
    name: 'Windy',
    tier: 'paid',
    type: 'tile',
    description: 'Animated wind, wave, and weather tile overlays.',
    website: 'https://api.windy.com',
    pros: ['Beautiful visualizations', 'Animated overlays', 'Multiple data layers'],
    cons: ['Expensive', 'API key required'],
    requiresApiKey: true,
    apiKeySignupUrl: 'https://api.windy.com/signup',
    pricingNote: '~$720/year',
  },
  {
    id: 'navionics',
    name: 'Navionics/Garmin',
    tier: 'paid',
    type: 'tile',
    description: 'Premium nautical charts with detailed depth contours and marina info.',
    website: 'https://www.navionics.com',
    pros: ['Industry-leading charts', 'Detailed depth data', 'Marina information'],
    cons: ['Expensive', 'Contact for pricing', 'Complex integration'],
    requiresApiKey: true,
    apiKeySignupUrl: 'https://developer.navionics.com',
    pricingNote: 'Contact Garmin/Navionics for pricing',
  },
  {
    id: 'marinetraffic',
    name: 'MarineTraffic',
    tier: 'paid',
    type: 'data',
    description: 'Global vessel tracking with satellite AIS coverage.',
    website: 'https://www.marinetraffic.com',
    pros: ['Global coverage', 'Satellite + terrestrial AIS', 'Historical data'],
    cons: ['Credit-based pricing', 'Can be expensive'],
    requiresApiKey: true,
    apiKeySignupUrl: 'https://www.marinetraffic.com/en/ais-api-services',
    pricingNote: 'Credit-based pricing, varies by endpoint',
  },
]

export const freeProviders = nauticalProviders.filter(p => p.tier === 'free')
export const paidProviders = nauticalProviders.filter(p => p.tier === 'paid')
export const getProvider = (id: string) => nauticalProviders.find(p => p.id === id)
